### ISSUE TITLE
pifpaf broken since 3.2 on debian bookwork (python3.11)

### ISSUE THREAD

**Issue by douardda** [jd/pifpaf#188]
From a fresh venv using system's python 3.11:

```
python3 -m venv test_pifpaf 
[...]
./test_pifpaf/bin/pip install -U pip
[...]
./test_pifpaf/bin/pip install pifpaf
[...]
./test_pifpaf/bin/pifpaf list
CRITICAL [root] Traceback (most recent call last):
  File "/home/ddouard/./test_pifpaf/bin/pifpaf", line 8, in <module>
    sys.exit(run_main())
             ^^^^^^^^^^
  File "/home/ddouard/test_pifpaf/lib/python3.11/site-packages/pifpaf/__main__.py", line 299, in run_main
    return main.main(standalone_mode=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddouard/test_pifpaf/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ddouard/test_pifpaf/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddouard/test_pifpaf/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddouard/test_pifpaf/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddouard/test_pifpaf/lib/python3.11/site-packages/pifpaf/__main__.py", line 122, in drivers_list
    for n in DAEMONS.keys():
             ^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'keys'

./test_pifpaf/bin/python -VV
Python 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
```

It works ok with pifpaf<3.2 

Thanks

**Comment by tobias-urdin** [comment]
thanks for your report! fixed in 3.2.3
